// Package idexport renders the managed identities as the id-assignment formats a
// directory service consumes, so the numbers usersync allocated can be carried
// into AD verbatim instead of being reassigned there.
//
// That "verbatim" is the whole point. Files are owned by numeric uid, and on a
// filesystem with snapshots the historical ones cannot be chown'd at all — so
// renumbering at the moment AD takes over would leave every snapshot pointing at
// an identity that no longer matches, which is the uid-reuse hazard the roster's
// tombstones exist to prevent. AD's idmap_ad backend reads uid/gid from the
// RFC2307 uidNumber/gidNumber attributes, so seeding those attributes with the
// numbers already in the ground makes the handover a no-op for every file.
package idexport

import (
	"encoding/csv"
	"fmt"
	"io"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/lesomnus/usersync/internal/roster"
)

// CSVHeader is the column order emitted by CSV. It is stable: the PowerShell in
// the docs binds to these names.
var CSVHeader = []string{"type", "name", "uid_number", "gid_number", "unix_home_directory", "login_shell"}

// entries returns the roster's groups and then its users, each sorted by name,
// with reserved users dropped.
//
// A reserved entry is a tombstone: it holds a uid so nobody else can be given
// it, but there is no account behind it and there will be none in the directory
// either, so there is nothing to seed. The uid stays blocked by the reservation
// of the whole id band, not by a per-user attribute — which is why the roster
// remains the ledger after the migration rather than being superseded by it.
func entries(ro *roster.Roster) (groups []roster.Group, users []roster.User) {
	groups = append(groups, ro.Groups...)
	sort.Slice(groups, func(i, j int) bool { return groups[i].Name < groups[j].Name })

	for _, u := range ro.Users {
		if u.Status == roster.Reserved {
			continue
		}
		users = append(users, u)
	}
	sort.Slice(users, func(i, j int) bool { return users[i].Name < users[j].Name })
	return groups, users
}

// CSV writes one row per group and per user, for `Set-ADGroup`/`Set-ADUser` to
// consume. Identity is the account NAME (sAMAccountName), not a distinguished
// name: PowerShell resolves the DN itself, so the export does not have to guess
// where in the directory tree an account lives.
//
// A user's gid_number is its uid: usersync gives every user a private group
// whose gid equals its uid, and that equality has to survive into AD or files in
// the home end up with a group that maps to nothing.
func CSV(w io.Writer, ro *roster.Roster, homeBase, shell string) error {
	groups, users := entries(ro)

	cw := csv.NewWriter(w)
	if err := cw.Write(CSVHeader); err != nil {
		return err
	}
	for _, g := range groups {
		if err := cw.Write([]string{"group", g.Name, "", u32(g.GID), "", ""}); err != nil {
			return err
		}
	}
	for _, u := range users {
		if err := cw.Write([]string{"user", u.Name, u32(u.UID), u32(u.UID), path.Join(homeBase, u.Name), shell}); err != nil {
			return err
		}
	}
	cw.Flush()
	return cw.Error()
}

// LDIF writes `changetype: modify` records setting uidNumber/gidNumber, for
// ldapmodify against a directory that already has the accounts.
//
// The DN is built as CN=<name>,<baseDN>. AD does NOT require an account's CN to
// equal its sAMAccountName — that holds for scripted creation and often not for
// accounts made through the GUI — so the header says so and the CSV path, which
// resolves identity by name, is the safer default.
func LDIF(w io.Writer, ro *roster.Roster, baseDN string) error {
	baseDN = strings.TrimSpace(baseDN)
	if baseDN == "" {
		return fmt.Errorf("ldif export needs a base DN (e.g. OU=Research,DC=corp,DC=example,DC=com)")
	}
	// The base DN is operator input pasted straight into the output; a newline in
	// it would end the record and let the rest be read as further LDIF directives.
	if i := strings.IndexFunc(baseDN, func(r rune) bool { return r < 0x20 || r == 0x7f }); i >= 0 {
		return fmt.Errorf("base DN must not contain control or newline characters")
	}

	groups, users := entries(ro)

	var b strings.Builder
	b.WriteString("# Generated by usersync — RFC2307 id attributes.\n")
	b.WriteString("# Apply with: ldapmodify -x -H ldaps://<dc> -D <bind-dn> -W -f <this file>\n")
	b.WriteString("#\n")
	b.WriteString("# Each DN below assumes the account's CN equals its name. Active Directory\n")
	b.WriteString("# does not guarantee that; verify (e.g. `dsquery user -samid <name>`) before\n")
	b.WriteString("# applying, or use `--format csv`, which resolves identity by name instead.\n")

	write := func(name string, attrs [][2]string) {
		fmt.Fprintf(&b, "\ndn: CN=%s,%s\n", escapeDN(name), baseDN)
		b.WriteString("changetype: modify\n")
		for i, a := range attrs {
			if i > 0 {
				b.WriteString("-\n")
			}
			fmt.Fprintf(&b, "replace: %s\n%s: %s\n", a[0], a[0], a[1])
		}
	}
	for _, g := range groups {
		write(g.Name, [][2]string{{"gidNumber", u32(g.GID)}})
	}
	for _, u := range users {
		// gidNumber mirrors uidNumber: see CSV.
		write(u.Name, [][2]string{{"uidNumber", u32(u.UID)}, {"gidNumber", u32(u.UID)}})
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func u32(v uint32) string { return strconv.FormatUint(uint64(v), 10) }

// escapeDN escapes a value for use inside a distinguished name, per RFC 4514.
//
// Names reaching this function are NOT the validated roster names: the export
// path builds its roster from a system scan, so a name comes out of getent
// exactly as /etc/group holds it — including whatever a hand edit put there,
// which is the same class of account `audit` reports as undeclared. An
// unescaped comma or plus would end the relative distinguished name early and
// make the record address a different object than the one it names, which
// ldapmodify would apply without complaint.
func escapeDN(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for i, r := range s {
		switch {
		// A leading '#' or space, and a trailing space, are only special at the
		// edges of the value.
		case i == 0 && (r == '#' || r == ' '),
			i == len(s)-1 && r == ' ':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r == '"' || r == '+' || r == ',' || r == ';' || r == '<' || r == '>' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r == 0:
			// NUL has no escaped literal form; the hex escape is the only option.
			b.WriteString("\\00")
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
